### PR TITLE
navbar updates

### PR DESCRIPTION
**Pull request by DevAdarsh0084**
navbar has been updated through gsap animation and a logo has been added as well

### CODE REVIEW

**Comment by pranitrathod** [comment]
There's a conflict in your PR
please check or I'll fix it @DevAdarsh0084

**Comment by DevAdarsh0084** [comment]
if you can then please or otherwise i will commit again and make a pr

**Comment by pranitrathod** [comment]
Please PR on WEB repo @DevAdarsh0084 
https://github.com/pranitrathod/Web

**Comment by pranitrathod** [comment]
Also follow the account for future open source contribution 
Thank you @DevAdarsh0084 
and ill fix  above conflict

**Comment by pranitrathod** [comment]
Hello @DevAdarsh0084 you have to PR on WEB for counting you contribution

**Comment by pranitrathod** [comment]
Also @DevAdarsh0084 follow @pranitrathod for more contributions

**Comment by pranitrathod** [comment]
I waited for 2 days,but didnt hear you back!

**Pull request closed without merging**
