### PR TITLE
ahmedraza

### PR DESCRIPTION
**Pull request by ahmedrazabaloch**
QuizApp uploaded 
please add hecktoberfest-accepted label

### CODE REVIEW

**Comment by pranitrathod** [comment]
Thanks for the enthusiasm @pranitrathod

**Comment by ahmedrazabaloch** [comment]
can you please add hectoberfest-accepted label it may help to get my point to participate open scores

**Comment by pranitrathod** [comment]
It's already labelled @ahmedrazabaloch 

Watch the repo labels

THANK YOU!

**Comment by pranitrathod** [comment]
@ahmedrazabaloch you have to follow my account for more contributions in future
Thank you!!

**Comment by ahmedrazabaloch** [comment]
@pranitrathod Can you guide me about hecktoberfest, am bignner and its my first time to participate in open source and hecktoberfest how to get my 4 pr with the right repo

**Comment by pranitrathod** [comment]
Sure @ahmedrazabaloch do more 3 PRs on your choice of programming my team will review it and will see if it's align with our terms
Soon you go to hacktoberfest website and see if your 4 PRs are merged
NOTE: YOU HAVE TO REGISTER FOR HACKTOBERFEST ON HACKTOBERFEST WEBSITE

**Comment by pranitrathod** [comment]
@ahmedrazabaloch my repo is best for any beginner out there
STAR the repo and encourage your other followers to star and folk this repo for there contribution

**Comment by ahmedrazabaloch** [comment]
@pranitrathod this repo EXCLUDED from hecktoberfest

**Comment by pranitrathod** [comment]
This is because you might given un- ethical naming of the repo @ahmedrazabaloch

**Comment by pranitrathod** [comment]
I'll create a new repo for you guys if you faced such issue and please name the repo and PR msg good,with intended contribution @ahmedrazabaloch

**Comment by pranitrathod** [comment]
Please PR your request code to this repo 
Thank you @ahmedrazabaloch 
https://github.com/pranitrathod/Web
and also remember to give valid PR name
For example: build new nav bar or create new feature

**Comment by pranitrathod** [comment]
@ahmedrazabaloch please follow the above mentioned repo

**Pull request merged**
