### PR TITLE
Sign-In page added

### PR DESCRIPTION
**Pull request by ahmedrazabaloch**
Sign-In page html css created with attractive UI

### CODE REVIEW

**Comment by pranitrathod** [comment]
Not on this repo @ahmedrazabaloch another one which I tagged you in one of our conversation,Do PR  there!

**Comment by ahmedrazabaloch** [comment]
😭how to get that repo

**Comment by pranitrathod** [comment]
I gave you the link there
Please check constantly your notification @ahmedrazabaloch

**Comment by ahmedrazabaloch** [comment]
ok got it thanks can i upload the same file there ?

**Comment by pranitrathod** [comment]
Sure! @pranitrathod

**Pull request closed without merging**
